LabNet2021.Tp8.API-MVC-FINAL/Models/Characters.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace LabNet2021.Tp8.API_MVC_FINAL.Models
{
    public class Characters
    {
        public string name { get; set; }
        public string species { get; set; }
        public string gender { get; set; }
        public string house { get; set; }
    }
}

LabNet2021.Tp8.API-MVC-FINAL/Models/CharactersView.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace LabNet2021.Tp8.API_MVC_FINAL.Models
{
    public class CharactersView
    {
        public string name { get; set; }
        public string species { get; set; }
        public string gender { get; set; }
        public string house { get; set; }
    }
}

LabNet2021.Tp8.API-MVC-FINAL/Controllers/CharactersController.cs
using LabNet2021.Tp8.API_MVC_FINAL.Models;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace LabNet2021.Tp8.API_MVC_FINAL.Controllers
{
    public class CharactersController : Controller
    {
        string Baseurl = "http://hp-api.herokuapp.com/";
        public async Task<ActionResult> Index()
        {
            List<CharactersView> CharInfo = new List<CharactersView>();
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri(Baseurl);
                client.DefaultRequestHeaders.Clear();

                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

                HttpResponseMessage Res = await client.GetAsync("api/characters");

                if (Res.IsSuccessStatusCode)
                {
                    var CharResponse = Res.Content.ReadAsStringAsync().Result;
                    CharInfo = JsonConvert.DeserializeObject<List<CharactersView>>(CharResponse);
                }
                return View(CharInfo);
            }
        }
    }
}

LabNet2021.Tp8.API-MVC-FINAL/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LabNet2021.Tp8.API_MVC_FINAL.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

LabNet2021.Tp8.API-MVC-FINAL/Views/Characters/Index.cshtml
@model IEnumerable<LabNet2021.Tp8.API_MVC_FINAL.Models.CharactersView>

@{
    ViewBag.Title = "Index";
}

<h2 class="h2">List of Characters in Harry Potter</h2>


<table id="characters" class="table table-hover">
    <thead class="">

        <tr>
            <th scope="col">
                @Html.DisplayNameFor(model => model.name)
            </th>
            <th scope="col">
                @Html.DisplayNameFor(model => model.species)
            </th>
            <th scope="col">
                @Html.DisplayNameFor(model => model.gender)
            </th>
            <th scope="col">
                @Html.DisplayNameFor(model => model.house)
            </th>
            
        </tr>

    </thead>

    <tbody>

        @foreach (var item in Model)
        {
            <tr>
                <th scope="row">
                    @Html.DisplayFor(modelItem => item.name)
                </th>
                <td>
                    @Html.DisplayFor(modelItem => item.species)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.gender)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.house)
                </td>
                
            </tr>
        }

    </tbody>

</table>

@section scripts
{

    <script>

        $(document).ready(function () {
            $('#characters').DataTable();
        });

    </script>
    
}

LabNet2021.Tp8.API-MVC-FINAL/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

LabNet2021.Tp8.API-MVC-FINAL/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

LabNet2021.Tp8.API-MVC-FINAL/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

LabNet2021.Tp8.API-MVC-FINAL/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("API", "Index", "Characters")</li>
                    
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Vitale Juan Manuel</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>